### PR TITLE
Fix yq issue with accessing root filesystem when installed via snap

### LINKED ISSUE #159: yq installed via snap store does not have permissions to /tmp directory
TL;DR : If we install yq via snap store on Fedora, it uses strict confinement policy which does not provide access to root (including /tmp). And this causes issues like : 

```
$ yq e ".current-context" "/tmp/tmp.QNwtlzJzZh/credentials/kubeconfig/compute/compute.kubeconfig.base"
Error: open /tmp/tmp.QNwtlzJzZh/credentials/kubeconfig/compute/compute.kubeconfig.base: no such file or directory
```

https://snapcraft.io/docs/snap-confinement
https://github.com/mikefarah/yq#snap-notes
https://github.com/mikefarah/yq/issues/786

### PR DESCRIPTION
**Pull request by bnallapeta**
Fixes #159.

### CODE REVIEW

File: images/access-setup/content/bin/setup_compute.sh [hunk 1]
```diff
@@ -109,7 +109,7 @@ init() {
 
 generate_compute_credentials() {
   current_context=$(kubectl config current-context)
-  compute_name="$(yq '.contexts[] | select(.name == "'"$current_context"'") | .context.cluster' "$KUBECONFIG" | sed 's/:.*//')"
+  compute_name="$(cat $KUBECONFIG | yq '.contexts[] | select(.name == "'"$current_context"'") | .context.cluster' | sed 's/:.*//')"
```
Comment (Roming22) [inline images/access-setup/content/bin/setup_compute.sh:112]: env var should be enclosed in `"`.

Comment (bnallapeta) [reply images/access-setup/content/bin/setup_compute.sh]: Done.

**Review by Roming22 — APPROVED** [review]
